volumes:
  romm-storage:
  romm-database:
  romm-resources:


networks:
  romm-network:
    driver: bridge

services:
  romm-core:
    restart: unless-stopped
    image: rommapp/romm:latest

    environment:
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_HOST=$DB_HOST
      - DB_PASSWD=$DB_PASSWD
      - ROMM_AUTH_SECRET_KEY=$ROMM_AUTH_SECRET_KEY
      - HASHEOUS_API_ENABLED=$HASHEOUS_API_ENABLED
      - RETROACHIEVEMENTS_API_KEY=$RETROACHIEVEMENTS_API_KEY
      - RETROACHIEVEMENTS_USERNAME=$RETROACHIEVEMENTS_USERNAME

    volumes:
      - romm-storage:/redis-data
      - /romm/assets:/romm/assets
      - /romm/config:/romm/config
      - /romm/library:/romm/library
      - romm-resources:/romm/resources

    ports:
      - 8080

    networks:
      - romm-network

    depends_on:
      romm-database:
        restart: true
        condition: service_healthy

  romm-database:
    image: mariadb:latest
    restart: unless-stopped

    environment:
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
      - MARIADB_DATABASE=$MARIADB_DATABASE
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD

    volumes:
      - romm-database:/var/lib/mysql

    networks:
      - romm-network

    healthcheck:
      retries: 5
      timeout: 5s
      interval: 10s
      start_period: 30s
      start_interval: 10s
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
